Repository WildCodeSchool/lyon-js-sept2020-p3-babily-front-office, pull requests merged in 2021-01, with the labels that each got.

#50 fix footer
  components/Footer.module.css
  components/Header.js
  components/Information.module.css
  components/Marques.js
  components/Marques.module.css
  package-lock.json
  public/images/backgroundWave.png
Labels: Ready for prod

#53 bandeau pga ehome ok
  components/Bandeau.js
  components/Bandeau.module.css
  components/CestQuoiBabily.js
  components/Layout.js
  pages/index.js
  public/images/background10.jpg
  public/images/bpi.png
  public/images/caf.png
  public/images/frenchTech.png
  public/images/french_tech.png
  public/images/inpi.png
Labels: ready for validation

#57 Cards ac
  components/cards.js
  components/cards.module.css
  package-lock.json
  pages/index.js
  public/images/temoignage.png
Labels: ready for validation

#61 Bulles svg
  components/LeSaviezVous.js
Labels: ready for validation

#67 espace pros
  components/CestSimpleAvecBabily.js
  components/CestSimpleAvecBabily.module.css
  pages/espacepro.js
  public/images/forme2_home.png
  public/images/forme3_home.png
Labels: Conflicts
